// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFxv-ktoXvGQ_4VXYVqb1wkwphQuxRGuY',
    appId: '1:768365491548:web:76a905c5656e917cde3d99',
    messagingSenderId: '768365491548',
    projectId: 'notepad-f545b',
    authDomain: 'notepad-f545b.firebaseapp.com',
    storageBucket: 'notepad-f545b.firebasestorage.app',
    measurementId: 'G-QZ61HP4LMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Vv_KWCdw_0yFEHgJhmtcub61R-2lR1w',
    appId: '1:768365491548:android:b1c8ad0e9efddcd3de3d99',
    messagingSenderId: '768365491548',
    projectId: 'notepad-f545b',
    storageBucket: 'notepad-f545b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKYGT3dg6ocQkSIfzUepJhSubYiwWsRuI',
    appId: '1:768365491548:ios:7f20ba4ed2383caade3d99',
    messagingSenderId: '768365491548',
    projectId: 'notepad-f545b',
    storageBucket: 'notepad-f545b.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFxv-ktoXvGQ_4VXYVqb1wkwphQuxRGuY',
    appId: '1:768365491548:web:e4ab12c835d74d83de3d99',
    messagingSenderId: '768365491548',
    projectId: 'notepad-f545b',
    authDomain: 'notepad-f545b.firebaseapp.com',
    storageBucket: 'notepad-f545b.firebasestorage.app',
    measurementId: 'G-F7T2812CZY',
  );
}
