// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhiiy09C4BOq0PHbQuTrPzASAm-VxDKfM',
    appId: '1:269280921586:web:21124767129c224bab4d6b',
    messagingSenderId: '269280921586',
    projectId: 'myfirebase-55321',
    authDomain: 'myfirebase-55321.firebaseapp.com',
    storageBucket: 'myfirebase-55321.firebasestorage.app',
    measurementId: 'G-4NRLE5HEK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Srk8b_qS4A1S5g8E_yO-7Pq1oT4vAMc',
    appId: '1:269280921586:android:e31ec1f955afeb31ab4d6b',
    messagingSenderId: '269280921586',
    projectId: 'myfirebase-55321',
    storageBucket: 'myfirebase-55321.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhiiy09C4BOq0PHbQuTrPzASAm-VxDKfM',
    appId: '1:269280921586:web:a53af90983df31acab4d6b',
    messagingSenderId: '269280921586',
    projectId: 'myfirebase-55321',
    authDomain: 'myfirebase-55321.firebaseapp.com',
    storageBucket: 'myfirebase-55321.firebasestorage.app',
    measurementId: 'G-VJ85X261DD',
  );
}
