// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQyltwha8TE8-nlEo5I6INwd6gA5PZ3Qo',
    appId: '1:776080845609:web:528e23652ae4a84766e538',
    messagingSenderId: '776080845609',
    projectId: 'notepad-app-2025',
    authDomain: 'notepad-app-2025.firebaseapp.com',
    storageBucket: 'notepad-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDb7L2_MJwgF1rXEFPOm5K5wINgfOoNTg',
    appId: '1:776080845609:android:528357cc1f4bbe5b66e538',
    messagingSenderId: '776080845609',
    projectId: 'notepad-app-2025',
    storageBucket: 'notepad-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEmxFlK_20qOxiSeabhbQfF8Le_KeVwa8',
    appId: '1:776080845609:ios:9fa5ffbc6e755cad66e538',
    messagingSenderId: '776080845609',
    projectId: 'notepad-app-2025',
    storageBucket: 'notepad-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.no',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQyltwha8TE8-nlEo5I6INwd6gA5PZ3Qo',
    appId: '1:776080845609:web:dbf2be2dfcd43cf266e538',
    messagingSenderId: '776080845609',
    projectId: 'notepad-app-2025',
    authDomain: 'notepad-app-2025.firebaseapp.com',
    storageBucket: 'notepad-app-2025.firebasestorage.app',
  );
}
